<<<<<<< HEAD
# Site settings
title: Art by Bex
email: bexmwarner@gmail.com
author: hiimbex

keywords: jekyll, jekyll theme, portfolio theme, artist theme
description: my art!!!

header: images/author.png


# Exclude our ruby stuff
exclude: [.bundle, .vendor, .bin, starving-artist.gemspec, bin, vendor, Gemfile, Gemfile.lock, Rakefile, s3_website.yml, starving-artist-jekyll-theme-*.gem]


# Build settings
markdown: kramdown
kramdown:
  input: GFM

theme: starving-artist-jekyll-theme

# Plugins
gems:
  - jekyll-feed

feed:
  path: atom.xml

include: ['_pages']

collections:
  - galleries

#### SEO Stuff
google_universal_analytics_cookiedomain: auto
facebook_locale: en_US
facebook_image: images/author.png                      #enter a default image (at least 200x200px) to use here for posts/pages that don't have one.
twitter_user: hiimbexo
twitter_card: true
twitter_image: images/author.png                       #enter a default image (at least 200x200px) to use here for posts/pages that don't have one.
=======
baseurl: ""
url: "http://hiimbex.me/art"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"

title: "Bex Warner"
author: "Bex Warner"
bio: "I am a software engineer and artist seeking to make the world a better place through open source and the uplifting of underrepresented groups in tech.<br/>All artwork belongs to me."
publicise: "Credit for this jekyll theme goes to <a href=\"https://github.com/ramswaroop/photography\">Ram Patra</a>"
social_urls:
  linkedin: "https://www.linkedin.com/in/bex-warner-a72ab1122/"
  github: "https://www.github.com/hiimbex"
  twitter: "https://www.twitter.com/hiimbexo"
>>>>>>> 76e01796c504ddddc2003b54961b6c131fa3bc0d
